### ISSUE TITLE
dradis nmap import fails

### ISSUE THREAD

**Issue by tjb6** [dradis/dradis-ce#363]
### Steps to reproduce

Import nmap xml data into Kali dradis
### Expected behavior
Data should import normally, creating nodes

### Actual behavior
Import fails, shows the following in the import log
[10:41:59] There was a fatal error processing your upload:
[10:41:59] undefined method `project_id' for #<Node:0x00007facc6578f08>
[10:42:00] /usr/lib/dradis/ruby/2.5.0/gems/activemodel-5.1.6/lib/active_model/attribute_methods.rb:432:in `method_missing'
[10:42:00] /usr/lib/dradis/ruby/2.5.0/bundler/gems/dradis-plugins-5ff9d71c05de/lib/dradis/plugins/content_service/nodes.rb:40:in `create_node'
[10:42:00] /usr/lib/dradis/ruby/2.5.0/bundler/gems/dradis-nmap-4dc26f25433a/lib/dradis/plugins/nmap/importer.rb:31:in `block in import'
[10:42:01] /usr/lib/dradis/ruby/2.5.0/gems/ruby-nmap-0.9.3/lib/nmap/xml.rb:293:in `block in each_host'

### System configuration
**Dradis version**: 3.10.0 from Kali package

**Ruby version**: 2.5.1

**OS version**: Kali rolling

**Comment by tjb6** [comment]
It happens with any nmap file.
I'm creating the nmap files by saving from zenmap

**Comment by rachkor** [comment]
@tjb6 Rachael with the Dradis support team here. I was reading through the thread and noticed `Dradis version: 3.10.0 from Kali package`. Could you try running the latest version from Git? https://dradisframework.com/ce/documentation/install_kali.html. My hunch is that Kali rolling grabbed Dradis at a point where the updates to `dradis-plugins` were ahead of the updates to `dradis-nmap`. This should be resolved in the latest version, we just need to get you there!

**Comment by tjb6** [comment]
Rachel,
That worked fine, the nmap output imports now
Thanks,
Tony
