### ISSUE TITLE
undefined method `keys' for ["tcp/80", [{"source"=>"nmap", "id"=>"tunnel", "output"=>"n/a"}]]:Array

### ISSUE THREAD

**Issue by jloehel** [dradis/dradis-ce#519]
### Steps to reproduce

I imported the attached nmap xml output and merged it with a node. It works as a node in output.plugin. I guess it's not correctly merging the stuff.
[10.11.1.10.xml.txt](https://github.com/dradis/dradis-ce/files/3667088/10.11.1.10.xml.txt)

### Expected behavior
dradis-ce shows the node without issues

### Actual behavior
dradis-ce expects a dictionary but the import created a Array

### Traceback
```
app/presenters/property_presenter.rb:33:in `value'
app/views/nodes/show.html.erb:59:in `block (2 levels) in _app_views_nodes_show_html_erb___499553603507753143_70342727480580'
app/helpers/snowcrash_helper.rb:40:in `present'
app/views/nodes/show.html.erb:57:in `block in _app_views_nodes_show_html_erb___499553603507753143_70342727480580'
app/views/nodes/show.html.erb:56:in `each'
app/views/nodes/show.html.erb:56:in `_app_views_nodes_show_html_erb___499553603507753143_70342727480580'
```

### System configuration
**Dradis version**: 3.14.0-0kali1

**Ruby version**: ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]

**OS version**:
```
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2019.4"
VERSION_ID="2019.4"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
```

Edit:
I think this is already fixed in 3.15: https://github.com/dradis/dradis-ce/commit/e8cf7b98768eecf62e208540684570b81c660de8
When will you release 3.15?

**Comment by jloehel** [comment]
I applied the patches. It works now. I am closing this issue.
