### ISSUE TITLE
Install failed in Kali Linux

### ISSUE THREAD

**Issue by greyleonie** [dradis/dradis-ce#892]
### Steps to reproduce
Execute './bin/setup' in 'dradis-ce' folder.                             

### Expected behavior
Install dradis-ce in Kali Linux.

### Actual behavior
```
$ ./bin/setup                                                                        
== Enabling default add-ons ==
== Installing dependencies ==
Resolving dependencies...
...
Using factory_bot_rails 5.1.1
Using rails_autolink 1.1.6
Using dradis-html_export 4.0.0
Installing nokogumbo 2.0.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
                                                                                                                                                                                 
    current directory: /home/kali/tools/dradis-ce/vendor/bundle/ruby/2.7.0/gems/nokogumbo-2.0.2/ext/nokogumbo
/usr/bin/ruby2.7 -I /usr/lib/ruby/vendor_ruby -r ./siteconf20210831-26840-rlmbat.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)2.7
/usr/lib/ruby/vendor_ruby/nokogiri/xml/xpath/syntax_error.rb:4:in `<module:XML>': XPath is not a class (TypeError)
/home/kali/tools/dradis-ce/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.11.4-x86_64-linux/lib/nokogiri/2.7/nokogiri.so:0: previous definition of XPath was here
        from /usr/lib/ruby/vendor_ruby/nokogiri/xml/xpath/syntax_error.rb:3:in `<module:Nokogiri>'
        from /usr/lib/ruby/vendor_ruby/nokogiri/xml/xpath/syntax_error.rb:2:in `<top (required)>'
        from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:96:in `require'
        from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:96:in `require'
        from /usr/lib/ruby/vendor_ruby/nokogiri/xml/xpath.rb:2:in `<top (required)>'
        from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:96:in `require'
        from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:96:in `require'
        from /usr/lib/ruby/vendor_ruby/nokogiri/xml.rb:21:in `<top (required)>'
        from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:96:in `require'
        from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:96:in `require'
        from /usr/lib/ruby/vendor_ruby/nokogiri.rb:36:in `<top (required)>'
        from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        from extconf.rb:4:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/kali/tools/dradis-ce/vendor/bundle/ruby/2.7.0/gems/nokogumbo-2.0.2 for inspection.
Results logged to /home/kali/tools/dradis-ce/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/nokogumbo-2.0.2/gem_make.out

  /usr/lib/ruby/vendor_ruby/rubygems/ext/builder.rb:91:in `run'
  /usr/lib/ruby/vendor_ruby/rubygems/ext/ext_conf_builder.rb:48:in `block in build'
  /usr/lib/ruby/2.7.0/tempfile.rb:291:in `open'
  /usr/lib/ruby/vendor_ruby/rubygems/ext/ext_conf_builder.rb:28:in `build'
  /usr/lib/ruby/vendor_ruby/rubygems/ext/builder.rb:157:in `build_extension'
  /usr/lib/ruby/vendor_ruby/rubygems/ext/builder.rb:191:in `block in build_extensions'
  /usr/lib/ruby/vendor_ruby/rubygems/ext/builder.rb:188:in `each'
  /usr/lib/ruby/vendor_ruby/rubygems/ext/builder.rb:188:in `build_extensions'
  /usr/lib/ruby/vendor_ruby/rubygems/installer.rb:821:in `build_extensions'
  /var/lib/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/rubygems_gem_installer.rb:66:in `build_extensions'
  /var/lib/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/rubygems_gem_installer.rb:26:in `install'
  /var/lib/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/source/rubygems.rb:192:in `install'
  /var/lib/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /var/lib/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /var/lib/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing nokogumbo (2.0.2), and Bundler cannot continue.

In Gemfile:
  sanitize was resolved to 5.2.1, which depends on
    nokogumbo

== Command ["bundle install"] failed ==
```
#### I found the two compoments are existed.
```
$ gem list --local | grep -E "nokogumbo|nokogiri" 
nokogiri (1.11.4, 1.11.1)
nokogumbo (2.0.2)
```

### System configuration
**Dradis version**:
```
$ git status
HEAD detached at v4.0.0
nothing to commit, working tree clean
```

**Ruby version**:
```
$ ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]
```

**OS version**:
```
$ uname -a
Linux kali 5.10.0-kali3-amd64 #1 SMP Debian 5.10.13-1kali1 (2021-02-08) x86_64 GNU/Linux
```

**Comment by woopz-ie** [comment]
Enountered the same issue and it appeared I also had the debian packaged nokogiri installed (1.11.1).
Can you try to remove it and run the dradis setup again?
`apt remove ruby-nokogiri`

**Comment by greyleonie** [comment]
> Enountered the same issue and it appeared I also had the debian packaged nokogiri installed (1.11.1).
> Can you try to remove it and run the dradis setup again?
> `apt remove ruby-nokogiri`

I don't remove 'ruby-nokogiri'. I install Dradis in Kali by 'sudo apt install dradis'. Kali has published Dradis package [here](https://www.kali.org/tools/dradis/) .

For Ubuntu, I Install [RVM](https://github.com/rvm/ubuntu_rvm) first, then follow the [guide](https://dradisframework.com/ce/documentation/install_git.html) to install Dradis.

**Comment by rachkor** [comment]
@greyleonie a few things! First, could you try installing Dradis on Kali with this guide? https://dradisframework.com/ce/documentation/install_kali.html. 

Next, assuming that you get the same error with the different install process, this looks like an issue installing the `nokogumbo` gem. Could you try walking through the steps outlined here? https://github.com/mastodon/mastodon/issues/14941. If that doesn't get us anywhere, it might be worth contacting `nokogumbo` directly: https://github.com/rubys/nokogumbo/issues

**Comment by greyleonie** [comment]
> @greyleonie a few things! First, could you try installing Dradis on Kali with this guide? https://dradisframework.com/ce/documentation/install_kali.html.
> 
> Next, assuming that you get the same error with the different install process, this looks like an issue installing the `nokogumbo` gem. Could you try walking through the steps outlined here? [mastodon/mastodon#14941](https://github.com/mastodon/mastodon/issues/14941). If that doesn't get us anywhere, it might be worth contacting `nokogumbo` directly: https://github.com/rubys/nokogumbo/issues

@rachkor Many thanks for your suggestion! 
The actual behavior of the issue is what happened when I was installing Dradis on Kali with the guide as follow.  
https://dradisframework.com/ce/documentation/install_kali.html

By now, I installed Dradis by Kali's offical package: https://www.kali.org/tools/dradis/, it works well.
```
sudo apt install dradis
```
@rachkor How about add this install method to the guide of 'Installing Dradis on Kali Linux' ?

I double checked the issue mastodon/mastodon#14941. It looks like the same issue. I think the issue may close.

**Comment by rachkor** [comment]
@greyleonie thanks for the update! I'll add that to our idea backlog to investigate adding in the future. For now, we recommend the git install process as it will allow you to run the latest changes. Let us know if you run into any other issues!
